# System/ Debloat
rm -rf */ROM/system/system/heimdallddata
rm -rf */ROM/system/system/hidden
rm -rf */ROM/system/system/imagefilter_program_binary
rm -rf */ROM/system/system/preload
rm -rf */ROM/system/system/voicecommanddata

# System/App Debloat

rm -rf */ROM/system/system/app/ARCore
rm -rf */ROM/system/system/app/ARDrawing
rm -rf */ROM/system/system/app/ARZone
rm -rf */ROM/system/system/app/AutomationTest_FB
rm -rf */ROM/system/system/app/BasicDreams
rm -rf */ROM/system/system/app/BBCAgent
rm -rf */ROM/system/system/app/BGMProvider
rm -rf */ROM/system/system/app/BixbyWakeup
rm -rf */ROM/system/system/app/BlockchainBasicKit
rm -rf */ROM/system/system/app/CameraExtensionsProxy
rm -rf */ROM/system/system/app/Cameralyzer
rm -rf */ROM/system/system/app/ccinfo
rm -rf */ROM/system/system/app/ChromeCustomizations
rm -rf */ROM/system/system/app/ClockPackage
rm -rf */ROM/system/system/app/DAAgent
rm -rf */ROM/system/system/app/DictDiotekForSec
rm -rf */ROM/system/system/app/ARCorDRParser
rm -rf */ROM/system/system/app/DsmsAPK
rm -rf */ROM/system/system/app/EasymodeContactsWidget81
rm -rf */ROM/system/system/app/EmergencyLauncher
rm -rf */ROM/system/system/app/ESEServiceAgent
rm -rf */ROM/system/system/app/FactoryAirCommandManager
rm -rf */ROM/system/system/app/FactoryCameraFB
rm -rf */ROM/system/system/app/Fast
rm -rf */ROM/system/system/app/FBAppManager_NS
rm -rf */ROM/system/system/app/Foundation
rm -rf */ROM/system/system/app/GalaxyResourceUpdater
rm -rf */ROM/system/system/app/GearManagerStub
rm -rf */ROM/system/system/app/GooglePrintRecommendationService
rm -rf */ROM/system/system/app/KidsHome_Installer
rm -rf */ROM/system/system/app/LiveTranscribe
rm -rf */ROM/system/system/app/MAPSAgent
rm -rf */ROM/system/system/app/MDMApp
rm -rf */ROM/system/system/app/MdxKitService
rm -rf */ROM/system/system/app/MinusOnePage
rm -rf */ROM/system/system/app/NfcNci/lib
rm -rf */ROM/system/system/app/ParentalCare
rm -rf */ROM/system/system/app/PlayAutoInstallConfig
rm -rf */ROM/system/system/app/PrintSpooler
rm -rf */ROM/system/system/app/Rampart
rm -rf */ROM/system/system/app/SafetyInformation
rm -rf */ROM/system/system/app/SamsungCalendar
rm -rf */ROM/system/system/app/SamsungOne
rm -rf */ROM/system/system/app/SamsungPassAutofill_v1
rm -rf */ROM/system/system/app/SamsungTTS*
rm -rf */ROM/system/system/app/SecFactoryPhoneTest
rm -rf */ROM/system/system/app/SecureElement
rm -rf */ROM/system/system/app/SetupWizardLegalProvider
rm -rf */ROM/system/system/app/SmartReminder
rm -rf */ROM/system/system/app/SmartSwitch*
rm -rf */ROM/system/system/app/StickerCenter
rm -rf */ROM/system/system/app/TEEgrisTuiService
rm -rf */ROM/system/system/app/Traceur
rm -rf */ROM/system/system/app/UnifiedWFC
rm -rf */ROM/system/system/app/UniversalMDMClient
rm -rf */ROM/system/system/app/VideoEditorLite_Dream_N
rm -rf */ROM/system/system/app/VisionIntelligence3.7
rm -rf */ROM/system/system/app/VoiceAccess
rm -rf */ROM/system/system/app/VTCameraSetting
rm -rf */ROM/system/system/app/WebManual
rm -rf */ROM/system/system/app/WifiGuider
rm -rf */ROM/system/system/app/WlanTest

# System/Bin Debloat

rm -rf */ROM/system/system/bin/kumihodecoder
rm -rf */ROM/system/system/bin/fabric_crypto

# System/CameraData Debloat

rm -rf */ROM/system/system/cameradata/portrait_data
rm -rf */ROM/system/system/cameradata/singletake
rm -rf */ROM/system/system/cameradata/aremoji-feature.xml
rm -rf */ROM/system/system/cameradata/camera-feature.xml

# System/Etc Debloat

rm -rf */ROM/system/system/etc/ailasso
rm -rf */ROM/system/system/etc/epdg
rm -rf */ROM/system/system/etc/kumiho
rm -rf */ROM/system/system/etc/mars
rm -rf */ROM/system/system/etc/theme
rm -rf */ROM/system/system/etc/floating_feature.xml
rm -rf */ROM/system/system/etc/init/fabric_crypto.rc
rm -rf */ROM/system/system/etc/init/kumioencoder.rc

# System/lib Debloat

rm -rf */ROM/system/system/lib/libofi*

# System/lib64 Debloat

rm -rf */ROM/system/system/lib64/libPortraitDistortionCorrection.arcsoft.so
rm -rf */ROM/system/system/lib64/libimage_enhancement.arcsoft.so
rm -rf */ROM/system/system/lib64/libGalleryDistortionCorrection.arcsoft.so
rm -rf */ROM/system/system/lib64/libhumantracking.arcsoft.so
rm -rf */ROM/system/system/lib64/libfacialrestoration.arcsoft.so
rm -rf */ROM/system/system/lib64/libGalleryDistortionDetector.arcsoft.so
rm -rf */ROM/system/system/lib64/libkumiho*
rm -rf */ROM/system/system/lib64/libofi*

# System/Priv-App Debloat

rm -rf */ROM/system/system/priv-app/AdaptSound_U
rm -rf */ROM/system/system/priv-app/AppUpdateCenter
rm -rf */ROM/system/system/priv-app/AREmoji
rm -rf */ROM/system/system/priv-app/AREmojiEditor
rm -rf */ROM/system/system/priv-app/AuthFramework
rm -rf */ROM/system/system/priv-app/AutoDoodle
rm -rf */ROM/system/system/priv-app/AvatarEmojiSticker
rm -rf */ROM/system/system/priv-app/BCService
rm -rf */ROM/system/system/priv-app/BeaconManager
rm -rf */ROM/system/system/priv-app/Bixby
rm -rf */ROM/system/system/priv-app/BixbyVisionFramework3.5
rm -rf */ROM/system/system/priv-app/BiometricSettings
rm -rf */ROM/system/system/priv-app/BuiltInPrintService
rm -rf */ROM/system/system/priv-app/CIDManager
rm -rf */ROM/system/system/priv-app/Crane
rm -rf */ROM/system/system/priv-app/DeviceBasedServiceConsent
rm -rf */ROM/system/system/priv-app/DeviceQualityAgent31
rm -rf */ROM/system/system/priv-app/DiagMonAgent91
rm -rf */ROM/system/system/priv-app/DigitalWellbeing
rm -rf */ROM/system/system/priv-app/DualOutFocusViewer_S
rm -rf */ROM/system/system/priv-app/DynamicLockscreen
rm -rf */ROM/system/system/priv-app/DynamicSystemInstallationService
rm -rf */ROM/system/system/priv-app/EasySetup
rm -rf */ROM/system/system/priv-app/EmergencySOS
rm -rf */ROM/system/system/priv-app/EpdgService
rm -rf */ROM/system/system/priv-app/EsimClient
rm -rf */ROM/system/system/priv-app/FacAtFunction
rm -rf */ROM/system/system/priv-app/FactoryTestProvider
rm -rf */ROM/system/system/priv-app/FBInstaller_NS
rm -rf */ROM/system/system/priv-app/FBServices
rm -rf */ROM/system/system/priv-app/Fmm
rm -rf */ROM/system/system/priv-app/FotaAgent
rm -rf */ROM/system/system/priv-app/GalleryWidget
rm -rf */ROM/system/system/priv-app/Game*
rm -rf */ROM/system/system/priv-app/GpuWatchApp
rm -rf */ROM/system/system/priv-app/HdmApk
rm -rf */ROM/system/system/priv-app/HwModuleTest
rm -rf */ROM/system/system/priv-app/IAFDManagerService
rm -rf */ROM/system/system/priv-app/IntelligentDynamicFpsService
rm -rf */ROM/system/system/priv-app/IpsGeofence
rm -rf */ROM/system/system/priv-app/KLMSAgent
rm -rf */ROM/system/system/priv-app/KmxService
rm -rf */ROM/system/system/priv-app/knoxanalyticsagent
rm -rf */ROM/system/system/priv-app/KnoxCore
rm -rf */ROM/system/system/priv-app/KnoxGuard
rm -rf */ROM/system/system/priv-app/KnoxMposAgent
rm -rf */ROM/system/system/priv-app/KnoxNetworkFilter
rm -rf */ROM/system/system/priv-app/knoxvpnproxyhandler
rm -rf */ROM/system/system/priv-app/KnoxZtFramework
rm -rf */ROM/system/system/priv-app/KPECore
rm -rf */ROM/system/system/priv-app/LinkToWindowsService
rm -rf */ROM/system/system/priv-app/MobileWips
rm -rf */ROM/system/system/priv-app/OdaService
rm -rf */ROM/system/system/priv-app/OMCAgent5
rm -rf */ROM/system/system/priv-app/OneDrive_Samsung_v3
rm -rf */ROM/system/system/priv-app/ONS
rm -rf */ROM/system/system/priv-app/PaymentFramework
rm -rf */ROM/system/system/priv-app/PhoneErrService
rm -rf */ROM/system/system/priv-app/PhotoRemasterService
rm -rf */ROM/system/system/priv-app/RubinVersion34
rm -rf */ROM/system/system/priv-app/SamsungBilling
rm -rf */ROM/system/system/priv-app/SamsungCamera
rm -rf */ROM/system/system/priv-app/SamsungCore*
rm -rf */ROM/system/system/priv-app/SamsungExperienceService
rm -rf */ROM/system/system/priv-app/SamsungIntelliVoiceServices
rm -rf */ROM/system/system/priv-app/SamsungMagnifier3
rm -rf */ROM/system/system/priv-app/SamsungPass
rm -rf */ROM/system/system/priv-app/SCPMAgent
rm -rf */ROM/system/system/priv-app/SDMConfig
rm -rf */ROM/system/system/priv-app/sec_camerax_service
rm -rf */ROM/system/system/priv-app/SecAppSeparation
rm -rf */ROM/system/system/priv-app/SecureFolder
rm -rf */ROM/system/system/priv-app/SEMFactoryApp
rm -rf */ROM/system/system/priv-app/SendHelpMessage
rm -rf */ROM/system/system/priv-app/SettingsBixby
rm -rf */ROM/system/system/priv-app/SingleTakeService
rm -rf */ROM/system/system/priv-app/SKMSAgent
rm -rf */ROM/system/system/priv-app/SmartEpdgTestApp
rm -rf */ROM/system/system/priv-app/SmartManager_v6_DeviceSecurity
rm -rf */ROM/system/system/priv-app/SmartSwitch*
rm -rf */ROM/system/system/priv-app/SmartThingsKit
rm -rf */ROM/system/system/priv-app/SOAgent7
rm -rf */ROM/system/system/priv-app/SPPPushClient
rm -rf */ROM/system/system/priv-app/StickerFaceARAvatar
rm -rf */ROM/system/system/priv-app/StoryService
rm -rf */ROM/system/system/priv-app/SumeNNService
rm -rf */ROM/system/system/priv-app/SVCAgent
rm -rf */ROM/system/system/priv-app/SVoiceIME
rm -rf */ROM/system/system/priv-app/TalkbackSE
rm -rf */ROM/system/system/priv-app/Upday
rm -rf */ROM/system/system/priv-app/YourPhone_P1_5

# System/SystemExt/Apex Debloat

rm -rf */ROM/system/system/system_ext/apex

# System/SystemExt/Priv-app Debloat

rm -rf */ROM/system/system/system_ext/priv-app/GoogleFeedback
rm -rf */ROM/system/system/system_ext/priv-app/SetupWizard