#!/bin/bash
# Script per modificare floating_feature.xml mantenendo l'indentazione originale

FILE="system_modified/system/etc/floating_feature.xml"

# ====== BLOCCO CAMERA ======
read -r -d '' NEW_CAMERA_BLOCK << 'EOF'
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_DEFLICKER>OFF</SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_DEFLICKER>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_HIGH_RESOLUTION_MAX_CAPTURE>1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_HIGH_RESOLUTION_MAX_CAPTURE>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_ARDOODLE_PEN_TYPE>3d,Pattern,Regular,Highlighter,Glass_lite,Text,Organic_lite</SEC_FLOATING_FEATURE_CAMERA_CONFIG_ARDOODLE_PEN_TYPE>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_AVATAR_MAX_FACE_NUM>1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_AVATAR_MAX_FACE_NUM>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_BOKEH>-1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_BOKEH>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_MACRO>-1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_MACRO>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE2>-1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE2>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_BINNING>-1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_BINNING>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP>-1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_UW>2</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_UW>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_WIDE>0</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_WIDE>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_CORE_VERSION>v2</SEC_FLOATING_FEATURE_CAMERA_CONFIG_CORE_VERSION>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE>0</SEC_FLOATING_FEATURE_CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_LLHDR_PROCESSING_TIMEOUT>2000</SEC_FLOATING_FEATURE_CAMERA_CONFIG_LLHDR_PROCESSING_TIMEOUT>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_MEMORY_USAGE_LEVEL>18</SEC_FLOATING_FEATURE_CAMERA_CONFIG_MEMORY_USAGE_LEVEL>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOIRE_REMOVAL>OFF</SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOIRE_REMOVAL>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE>[[3,1]]</SEC_FLOATING_FEATURE_CAMERA_CONFIG_MOTIONPHOTO_CAPTURE_MODE>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_MYFILTER>1,1,0</SEC_FLOATING_FEATURE_CAMERA_CONFIG_MYFILTER>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_BEAUTY_LEVEL>2</SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_BEAUTY_LEVEL>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT>80</SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_QRCODE_INTERVAL>500</SEC_FLOATING_FEATURE_CAMERA_CONFIG_QRCODE_INTERVAL>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_STRIDE_OCR_VERSION>V1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_STRIDE_OCR_VERSION>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_SUPERSTEADY_POPUP>-256</SEC_FLOATING_FEATURE_CAMERA_CONFIG_SUPERSTEADY_POPUP>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_UW_DISTORTION_CORRECTION>0,109,1,22010501,3264,2448,0,0,0,0</SEC_FLOATING_FEATURE_CAMERA_CONFIG_UW_DISTORTION_CORRECTION>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_VENDOR_LIB_INFO>beauty.samsung.v4,face_landmark.arcsoft.v2_1,single_bokeh.samsung.v2,facial_attribute.samsung.v1,food.samsung.v1,event_detection.samsung.v2,mfhdr.arcsoft.v1,llhdr.arcsoft.v1,hifills.mpi.v1,image_codec.samsung.v1,human_tracking_face.arcsoft.v2_1,localtm.samsung.v1_1</SEC_FLOATING_FEATURE_CAMERA_CONFIG_VENDOR_LIB_INFO>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_VERSION_FILTER_PROVIDER>7</SEC_FLOATING_FEATURE_CAMERA_CONFIG_VERSION_FILTER_PROVIDER>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION>0,0,0,0,0,0,0,0,0,0</SEC_FLOATING_FEATURE_CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION>
<SEC_FLOATING_FEATURE_CAMERA_CONFIG_WINE_DETECTOR>OFF</SEC_FLOATING_FEATURE_CAMERA_CONFIG_WINE_DETECTOR>
<SEC_FLOATING_FEATURE_CAMERA_DOCUMENTSCAN_SOLUTIONS>CV_DEWARPING</SEC_FLOATING_FEATURE_CAMERA_DOCUMENTSCAN_SOLUTIONS>
<SEC_FLOATING_FEATURE_CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE>V1</SEC_FLOATING_FEATURE_CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AFSKIP>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AFSKIP>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AI_HIGH_RESOLUTION_DRAFT_DOWNSCALE>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AVATAR>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_AVATAR>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_DOWNLOAD_EFFECT>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_DOWNLOAD_EFFECT>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_NIGHT_FRONT_DISPLAY_FLASH>true</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_NIGHT_FRONT_DISPLAY_FLASH>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_QRCODE>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_QRCODE>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_TORCH_BRIGHTNESS_LEVEL>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_TORCH_BRIGHTNESS_LEVEL>
<SEC_FLOATING_FEATURE_CAMERA_SUPPORT_VIDEO_PALM>TRUE</SEC_FLOATING_FEATURE_CAMERA_SUPPORT_VIDEO_PALM>
EOF

# ====== ESECUZIONE ======
awk -v block="$NEW_CAMERA_BLOCK" '
    BEGIN { replaced_camera=0 }
    {
        # Blocco CAMERA
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_CAMERA/) {
            if (!replaced_camera) {
                indent = match($0, /[^ \t]/)
                prefix = substr($0, 1, indent-1)
                n = split(block, lines, "\n")
                for (i = 1; i <= n; i++)
                    if (length(lines[i]) > 0)
                        print prefix lines[i]
                replaced_camera=1
            }
            next
        }

        # AUDIO
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>/) {
            sub(/<SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>.*/, "<SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>eq_custom,uhq_upscale,uhq_onoff,karaoke,adapt,spk_stereo,dolby_game_spk_off</SEC_FLOATING_FEATURE_AUDIO_CONFIG_SOUNDALIVE_VERSION>")
        }

        # SYSTEM SIOP
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME>/) {
            sub(/<SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME>.*/, "<SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME>siop_default</SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME>")
        }

        # SETTINGS ELECTRIC
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE>/) {
            sub(/<SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE>.*/, "<SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE>DC 9 V; 1.67 A</SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE>")
        }

        # LOCKSCREEN STYLE
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE>/) {
            sub(/<SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE>.*/, "<SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE>MOTION,VIDEO,COVER_MP4</SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE>")
        }

        # LCD CONFIG AOD
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_FULLSCREEN>/) {
            sub(/<SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_FULLSCREEN>.*/, "<SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_FULLSCREEN>1</SEC_FLOATING_FEATURE_LCD_CONFIG_AOD_FULLSCREEN>")
        }

        # LCD BLUE FILTER
        if ($0 ~ /^[ \t]*<SEC_FLOATING_FEATURE_LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE>/) {
            sub(/<SEC_FLOATING_FEATURE_LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE>.*/, "<SEC_FLOATING_FEATURE_LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE>0</SEC_FLOATING_FEATURE_LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE>")
        }

        print
    }
' "$FILE" > "${FILE}.tmp" && mv "${FILE}.tmp" "$FILE"

echo "✅ Tutte le sostituzioni completate in $FILE"
