# System/App Debloat

rm -rf a53/ROM/system/system/app/ARCore
rm -rf a53/ROM/system/system/app/ARDrawing
rm -rf a53/ROM/system/system/app/ARZone
rm -rf a53/ROM/system/system/app/AutomationTest_FB
rm -rf a53/ROM/system/system/app/BasicDreams
rm -rf a53/ROM/system/system/app/BBCAgent
rm -rf a53/ROM/system/system/app/BGMProvider
rm -rf a53/ROM/system/system/app/BixbyWakeup
rm -rf a53/ROM/system/system/app/BlockchainBasicKit
rm -rf a53/ROM/system/system/app/CameraExtensionsProxy
rm -rf a53/ROM/system/system/app/Cameralyzer
rm -rf a53/ROM/system/system/app/ccinfo
rm -rf a53/ROM/system/system/app/ChromeCustomizations
rm -rf a53/ROM/system/system/app/ClockPackage
rm -rf a53/ROM/system/system/app/DAAgent
rm -rf a53/ROM/system/system/app/DictDiotekForSec
rm -rf a53/ROM/system/system/app/ARCorDRParser
rm -rf a53/ROM/system/system/app/DsmsAPK
rm -rf a53/ROM/system/system/app/EasymodeContactsWidget81
rm -rf a53/ROM/system/system/app/EmergencyLauncher
rm -rf a53/ROM/system/system/app/ESEServiceAgent
rm -rf a53/ROM/system/system/app/FactoryAirCommandManager
rm -rf a53/ROM/system/system/app/FactoryCameraFB
rm -rf a53/ROM/system/system/app/Fast
rm -rf a53/ROM/system/system/app/FBAppManager_NS
rm -rf a53/ROM/system/system/app/Foundation
rm -rf a53/ROM/system/system/app/GalaxyResourceUpdater
rm -rf a53/ROM/system/system/app/GearManagerStub
rm -rf a53/ROM/system/system/app/GooglePrintRecommendationService
rm -rf a53/ROM/system/system/app/KidsHome_Installer
rm -rf a53/ROM/system/system/app/LiveTranscribe
rm -rf a53/ROM/system/system/app/MAPSAgent
rm -rf a53/ROM/system/system/app/MDMApp
rm -rf a53/ROM/system/system/app/MdxKitService
rm -rf a53/ROM/system/system/app/MinusOnePage
rm -rf a53/ROM/system/system/app/ParentalCare
rm -rf a53/ROM/system/system/app/PlayAutoInstallConfig
rm -rf a53/ROM/system/system/app/PrintSpooler
rm -rf a53/ROM/system/system/app/Rampart
rm -rf a53/ROM/system/system/app/SafetyInformation
rm -rf a53/ROM/system/system/app/SamsungCalendar
rm -rf a53/ROM/system/system/app/SamsungOne
rm -rf a53/ROM/system/system/app/SamsungPassAutofill_v1
rm -rf a53/ROM/system/system/app/SamsungTTS*
rm -rf a53/ROM/system/system/app/SecFactoryPhoneTest
rm -rf a53/ROM/system/system/app/SecureElement
rm -rf a53/ROM/system/system/app/SetupWizardLegalProvider
rm -rf a53/ROM/system/system/app/SmartReminder
rm -rf a53/ROM/system/system/app/SmartSwitch*
rm -rf a53/ROM/system/system/app/StickerCenter
rm -rf a53/ROM/system/system/app/TEEgrisTuiService
rm -rf a53/ROM/system/system/app/Traceur
rm -rf a53/ROM/system/system/app/UnifiedWFC
rm -rf a53/ROM/system/system/app/UniversalMDMClient
rm -rf a53/ROM/system/system/app/VideoEditorLite_Dream_N
rm -rf a53/ROM/system/system/app/VisionIntelligence3.7
rm -rf a53/ROM/system/system/app/VoiceAccess
rm -rf a53/ROM/system/system/app/VTCameraSetting
rm -rf a53/ROM/system/system/app/WebManual
rm -rf a53/ROM/system/system/app/WifiGuider
rm -rf a53/ROM/system/system/app/WlanTest