name: Download e Estrai Firmware Samsung

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno a mezzanotte
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  download_firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Scarica Firmware
      run: |
        # Usando curl per scaricare il firmware da una URL
        curl -L "URL_DEL_FIRMWARE" -o firmware.zip

    - name: Estrai Firmware
      run: |
        # Estrai il firmware se è in formato zip
        unzip firmware.zip -d firmware_extracted/

    - name: Carica Firmware Estratto (opzionale)
      uses: actions/upload-artifact@v2
      with:
        name: firmware-extracted
        path: firmware_extracted/
