name: A53 Port Exynos7904

on:  
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  download_firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Scarica Firmware
      run: |
        # Usando curl per scaricare il firmware da una URL
        curl -L https://download1588.mediafire.com/b9bfuygi624gR1M7oxd0SxSvcbVht2JLF8r9fld8WCF9_Uc_Qo1Yz79gHr18JXwe-7avp7GNxdT1fUKZumnziWXEZG1btQXyYla_gZMcsSBthJymLLOPQ0HZ1AVJQMWU9YrF6Wk1_toIIMEoGiGC_V9VwY1xIdDn-FnH4TjeHXvqqA/9hswk9rt13x9km2/a53.zip -o a53/ROM/system.zip

    - name: Estrai Firmware.zip
      run: |
        # Estrai il firmware se è in formato zip
        unzip a53/ROM/system.zip -d a53/ROM/ && rm -rf a53/ROM/system.zip

    - name: Debloat
      run: |
        # Esegui il debloat
        chmod +x script/system/debloat.sh && ./script/system/debloat.sh

    - name: Prop
      run: |
        # Modifica i build.prop
        chmod +x script/system/prop.sh && ./script/system/prop.sh

    - name: Common
      run: |
        # Copia i file comuni nella rom
        chmod +x script/system/common.sh && ./script/system/common.sh

    - name: Fix
      run: |
        # Esegui i fix
        chmod +x script/system/fix.sh && ./script/system/fix.sh

    - name: Comprimi ROM
      run: |
        # Comprimi la rom
        zip -r -9 -FS A53_Port.zip a53/ROM && rm -rf a53/ROM/system

    - name: Setup SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SF_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts

    - name: Upload firmware files to SourceForge
      run: |
          scp A53_Port.zip thewinner02@frs.sourceforge.net:/home/frs/project/oneui-ports/test/ && rm -rf a53/ROM/A53_Port.zip
          
