name: S23 FE Port Universal7885

on:  
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  build_s23fe_port:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Scarica Firmware
      run: |
        # Usando curl per scaricare il firmware da una URL
        curl -L https://download948.mediafire.com/0seejdu3sw5gKR2yJY9NPJeJmVhcTwN6hYDn_XOANlA-hC-D5UGVN4WSEXFu_z7jIMBr2zYViDOYFOLEitrvtqG973n07cwy8L0PVT8LSO63Ia-nsvtrypJfefgKHcKYOp64VleRR0e5AUzj4-4EGjPXA7IJ4C4OU9IQoZgkaWoZlQ/qv4kn0s33tx9exc/s23fe_port.zip -o s23fe/ROM/system.zip

    - name: Estrai Firmware.zip
      run: |
        # Estrai il firmware se è in formato zip
        unzip s23fe/ROM/system.zip -d s23fe/ROM/ && rm -rf s23fe/ROM/system.zip

    - name: Debloat
      run: |
        # Esegui il debloat
        chmod +x script/system/s23fe_debloat.sh && ./script/system/s23fe_debloat.sh

    - name: Common
      run: |
        # Copia i file comuni nella rom
        chmod +x script/system/s23fe_common.sh && ./script/system/s23fe_common.sh

    - name: Fix
      run: |
        # Esegui i fix
        chmod +x script/system/s23fe_fix.sh && ./script/system/s23fe_fix.sh

    - name: Comprimi ROM
      run: |
        # Comprimi la rom
        cd s23fe/ROM
        zip -r -9 -FS s23fe_Port.zip device META-INF product system vendor RAMDisk.img && rm -rf s23fe/ROM/system

    - name: Setup SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SF_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts

    - name: Upload firmware files to SourceForge
      run: |
          scp s23fe/ROM/s23fe_Port.zip thewinner02@frs.sourceforge.net:/home/frs/project/oneui-ports/test/ && rm -rf s23fe_Port.zip
          
