name: A53 Port Universal7885

on:  
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  download_firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Scarica Firmware
      run: |
        # Usando curl per scaricare il firmware da una URL
        curl -L https://download1588.mediafire.com/vfanrvvwh2qgLuRVZVYonMLyGsgsj_EZbb61pHhc5vF9XMp8ic_fWSvlXJEEWWPG35qqAHMrmnvpYO_Ci-Rt8FQLGsKBq-DNnlL7u2t1A2PqpJnRlr6TPQizZuKgB6QwbIjAixmiXF-Vu4NLMJqVDpmfYeQ33BO7DJtYUunf69Y_SA/9hswk9rt13x9km2/a53.zip -o a53/ROM/system.zip

    - name: Estrai Firmware.zip
      run: |
        # Estrai il firmware se è in formato zip
        unzip a53/ROM/system.zip -d a53/ROM/ && rm -rf a53/ROM/system.zip

    - name: Debloat
      run: |
        # Esegui il debloat
        chmod +x script/system/debloat.sh && ./script/system/debloat.sh